#!/usr/bin/env node
/**
 * build-friends.js
 * Scans all issues with the "approved" label, extracts fields,
 * and generates src/data/friends.ts
 *
 * Environment variables (passed by Actions workflow):
 *   GH_TOKEN          - GitHub Token for API calls
 *   ISSUES_REPO       - Repository to scan, format: owner/repo
 *   APPROVED_LABEL    - Label name for approved friend links
 *   OWNER_LOGIN       - Repo owner's GitHub username (for /tags directive)
 *   DEFAULT_TAGS      - Default tags as JSON array string, e.g. '["Friends"]'
 *   OUTPUT_FILE       - Output file path
 */

import { execSync } from "child_process";
import fs from "fs";

// ─── Read environment variables ───────────────────────────────────────────────
const GH_TOKEN       = process.env.GH_TOKEN;
const ISSUES_REPO    = process.env.ISSUES_REPO;
const APPROVED_LABEL = process.env.APPROVED_LABEL;
const OWNER_LOGIN    = process.env.OWNER_LOGIN;
const DEFAULT_TAGS   = JSON.parse(process.env.DEFAULT_TAGS || '["Friends"]');
const OUTPUT_FILE    = process.env.OUTPUT_FILE || "src/data/friends.ts";

if (!GH_TOKEN || !ISSUES_REPO || !APPROVED_LABEL || !OWNER_LOGIN) {
  console.error("❌ Missing required environment variables");
  process.exit(1);
}

// ─── GitHub API helper ────────────────────────────────────────────────────────
function ghApi(path) {
  const result = execSync(
    `gh api "${path}" --paginate`,
    { env: { ...process.env, GH_TOKEN }, encoding: "utf-8" }
  );
  return JSON.parse(result);
}

// ─── Parse issue form body ────────────────────────────────────────────────────
// GitHub issue forms render body as:
// ### Field Label
// Field Value
function parseIssueBody(body) {
  const fields = {};
  if (!body) return fields;
  const blocks = body.split(/^### /m).filter(Boolean);
  for (const block of blocks) {
    const lines = block.split("\n").map((l) => l.trim());
    const key = lines[0].trim();
    const value = lines.slice(1).find((l) => l.length > 0) || "";
    fields[key] = value;
  }
  return fields;
}

// ─── Extract /tags directive from owner's comments ────────────────────────────
// Format: /tags: Friends, Tech
// Only trusts comments from OWNER_LOGIN; uses last occurrence
function extractTagsFromComments(comments) {
  const ownerComments = comments
    .filter((c) => c.user.login === OWNER_LOGIN)
    .reverse();
  for (const comment of ownerComments) {
    const match = comment.body.match(/^\/tags:\s*(.+)$/m);
    if (match) {
      return match[1].split(",").map((t) => t.trim()).filter(Boolean);
    }
  }
  return null;
}

// ─── Generate friends.ts content ─────────────────────────────────────────────
function generateFriendsTs(items) {
  const itemsCode = items
    .map(
      (item) => `\t{
\t\tid: ${item.id},
\t\ttitle: ${JSON.stringify(item.title)},
\t\timgurl: ${JSON.stringify(item.imgurl)},
\t\tdesc: ${JSON.stringify(item.desc)},
\t\tsiteurl: ${JSON.stringify(item.siteurl)},
\t\ttags: ${JSON.stringify(item.tags)},
\t}`
    )
    .join(",\n");

  return `// Friend link data
// ⚠️ This file is auto-generated by GitHub Actions. Do not edit manually.
// Source: https://github.com/${ISSUES_REPO}/issues

export interface FriendItem {
\tid: number;
\ttitle: string;
\timgurl: string;
\tdesc: string;
\tsiteurl: string;
\ttags: string[];
}

export const friendsData: FriendItem[] = [
${itemsCode}
];

export function getFriendsList(): FriendItem[] {
\treturn friendsData;
}

export function getShuffledFriendsList(): FriendItem[] {
\tconst shuffled = [...friendsData];
\tfor (let i = shuffled.length - 1; i > 0; i--) {
\t\tconst j = Math.floor(Math.random() * (i + 1));
\t\t[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
\t}
\treturn shuffled;
}
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`📋 Scanning: ${ISSUES_REPO}`);
  console.log(`🏷️  Approved label: ${APPROVED_LABEL}`);
  console.log(`👤 Owner: ${OWNER_LOGIN}\n`);

  const issues = ghApi(
    `/repos/${ISSUES_REPO}/issues?labels=${encodeURIComponent(APPROVED_LABEL)}&state=open&per_page=100`
  );

  console.log(`✅ Found ${issues.length} approved friend link(s)`);

  const friendItems = [];
  for (const issue of issues) {
    console.log(`\n🔍 Processing #${issue.number}: ${issue.title}`);

    const fields = parseIssueBody(issue.body);
    const title   = fields["站点名称"];
    const siteurl = fields["站点链接"];
    const imgurl  = fields["头像链接"];
    const desc    = fields["站点描述"];

    if (!title || !siteurl || !imgurl || !desc) {
      console.warn(`   ⚠️  Incomplete fields, skipping`);
      continue;
    }

    const comments = ghApi(`/repos/${ISSUES_REPO}/issues/${issue.number}/comments`);
    const tags = extractTagsFromComments(comments) ?? DEFAULT_TAGS;

    console.log(`   title:   ${title}`);
    console.log(`   siteurl: ${siteurl}`);
    console.log(`   tags:    ${tags.join(", ")}`);

    friendItems.push({ id: issue.number, title, siteurl, imgurl, desc, tags });
  }

  const tsContent = generateFriendsTs(friendItems);

  // Ensure output directory exists
  const outputDir = OUTPUT_FILE.substring(0, OUTPUT_FILE.lastIndexOf("/"));
  if (outputDir) fs.mkdirSync(outputDir, { recursive: true });

  fs.writeFileSync(OUTPUT_FILE, tsContent, "utf-8");
  console.log(`\n📄 Generated: ${OUTPUT_FILE} (${friendItems.length} entries)`);
}

main().catch((err) => {
  console.error("❌ Build failed:", err.message);
  process.exit(1);
});
